openapi: 3.0.0
info:
  title: Echo
  version: "1.0"
servers:
  - url: https://postman-echo.com
paths:
  /get:
    get:
      operationId: echoGet
      parameters:
        - name: echo
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
